#!/usr/bin/env python3
# gen_isr_stubs.py — generates kernel/src/cpu/isr_stubs.S
# Run: python3 gen_isr_stubs.py  OR  make generate_stubs

import os

# Vectors where the CPU pushes an error code automatically (Intel SDM Vol.3A)
EC_VECTORS = {8, 10, 11, 12, 13, 14, 17, 21, 29, 30}

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'isr_stubs.S')

def main():
    lines = []
    lines.append("""\
// AUTO-GENERATED by gen_isr_stubs.py — do not edit by hand.
// Regenerate with: python3 gen_isr_stubs.py

.intel_syntax noprefix
.code64

// ---------------------------------------------------------------------------
// isr_common_stub — tail shared by all 256 handlers
// ---------------------------------------------------------------------------
.global isr_common_stub
isr_common_stub:
    test QWORD PTR [rsp + 24], 3
    jz   1f
    swapgs
1:
    push rax
    push rbx
    push rcx
    push rdx
    push rsi
    push rdi
    push rbp
    push r8
    push r9
    push r10
    push r11
    push r12
    push r13
    push r14
    push r15

    cld
    mov  rdi, rsp
    call isr_dispatch

    pop  r15
    pop  r14
    pop  r13
    pop  r12
    pop  r11
    pop  r10
    pop  r9
    pop  r8
    pop  rbp
    pop  rdi
    pop  rsi
    pop  rdx
    pop  rcx
    pop  rbx
    pop  rax

    test QWORD PTR [rsp + 24], 3
    jz   2f
    swapgs
2:
    add  rsp, 16        // discard vector + error_code
    iretq

// ---------------------------------------------------------------------------
// Per-vector stubs
// ---------------------------------------------------------------------------
""")

    for v in range(256):
        lines.append(f".global isr_stub_{v}\n")
        lines.append(f"isr_stub_{v}:\n")
        if v not in EC_VECTORS:
            lines.append("    push 0\n")
        lines.append(f"    push {v}\n")
        lines.append("    jmp  isr_common_stub\n\n")

    lines.append('.section .note.GNU-stack,"",@progbits\n')

    with open(OUT, 'w') as f:
        f.write(''.join(lines))
    print(f"[gen_isr_stubs] Wrote 256 stubs → {OUT}")

if __name__ == '__main__':
    main()
